name: test
on: [ push,pull_request ]

defaults:
  run:
    working-directory: backend

jobs:
  Backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: "./backend/yarn.lock"
      - name: Test backend
        run: |
          ls
          yarn --frozen-lockfile
          yarn test:all-test